title: Kuhyeun Ko
url: "https://kuhyeun-ko.github.io"
baseurl: ""

markdown: kramdown
# ins_logo: "./bits-logo.png"

tracking_id: #

# footer: yes
# footer: no
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "/khko/cv.pdf"
 - name: "Github"
   link: "https://github.com/kuhyeun-ko"
 - name: "Contact"
   link: "mailto:khko@unist.ac.kr"
